DELETE FROM PEDIDO
WHERE DATAPEDIDO < CURRENT_TIMESTAMP - 365;

delete FROM pedidoitem
WHERE IDPEDIDO NOT IN (SELECT CONTADOR FROM PEDIDO);

DELETE from eventooperador
WHERE DATA < CURRENT_TIMESTAMP - 60;
